# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'QiitaClieant' do
pod 'MagicalRecord'
pod 'Alamofire', '~> 1.2'
pod 'SwiftyJSON', '~> 2.2.0'
pod 'SVProgressHUD'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'MLFlyOverMenu'
end

target 'QiitaClieantTests' do

end

